# Cloud Build configuration for deploying backend and frontend to Cloud Run
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/brandstream-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/brandstream-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/brandstream-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/brandstream-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/brandstream-backend:$COMMIT_SHA'
    id: 'push-backend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/brandstream-frontend:$COMMIT_SHA'
    id: 'push-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'brandstream-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/brandstream-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'brandstream@thg-ml-dev.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,LOCATION=${_REGION}'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
    id: 'deploy-backend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'brandstream-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/brandstream-frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'brandstream@thg-ml-dev.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
    id: 'deploy-frontend'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/brandstream-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/brandstream-backend:latest'
  - 'gcr.io/$PROJECT_ID/brandstream-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/brandstream-frontend:latest'

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _BACKEND_URL: 'https://brandstream-backend-XXXXXXXXXX-uc.a.run.app'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

